export const TLI_NOTE_PATH_DEFAULT="Central Note.md"
export const LINKED_TO=" => "
export const LINKED_FROM=" <= "
export const LINKED_TLI="None"
export const LINKED_BOTH=" <=> "
export const TLI_VIEW_TYPE = "Automatic-MOC"
